### PR TITLE
replace image resources with Gtk widgets

### PR DESCRIPTION
**Pull request by hzulla**
Hi,

`kano-updater-gui` displays a fake GUI by using text stored as bitmaps in [images](https://raw.githubusercontent.com/KanoComputing/kano-updater/89e2c36a986e053a480e8ced44c35c43f46e8377/images/header/header-5.png), which makes the application [not translatable](https://github.com/KanoComputing/kano-updater/issues/50).

This patch replaces the images with Gtk widgets. It's a close, but obviously not an exact replica of the original layout:

stage5

As requested by @TommySaehl, the labels are using the Bariol font now. It [is not possible to define a line-height](http://stackoverflow.com/questions/25139645/gtk3-label-line-spacing) for Gtk.Label, but imho the layout still looks ok. (I tried using a Gtk.TextView instead, but that resulted in messier code.)

A nice side-effect is that it's now easy to change the poster text copy.

Please note that `current_number` is now 0-5 instead of 1-6 inside `kano-updater-gui`, which made the code easier to read.

What's not to like? The code contains a fair number of hard-coded layout definitions. No idea if these can be moved to the CSS instead.

### CODE REVIEW

**Comment by hzulla** [comment]
Note that the psa-label ("DO NOT DISCONNECT") has a different colour compared to the (!) image. This is because the (!) is actually bright white ffffff with transparency, while the label is using CSS lightgray d3d3d3. Needs to be fixed.

**Comment by tombettany** [comment]
Wow @hzulla great work! I'll try this out now.

**Comment by tombettany** [comment]
@hzulla This is AWESOME! Great work - I love the slide transitions.

@carolineclark Any objections to merging this?

@TommySaehl Is this close enough to the original design?

**Comment by carolineclark** [comment]
If it works, then no objections :)

**Comment by tombettany** [comment]
@FMog I'll rebuild the package now. Can you test when this is done?

**Comment by tombettany** [comment]
@FMog Package is built and available in the devel suite whenever you get a chance to update and test.

**Comment by hzulla** [comment]
Please proofread. Typos are possible. :-)

**Comment by TommySaehl** [comment]
Ah @hzulla , looks great man! Its close to shippable, just some tweaks;
The above image is the updater with my changes, and below I point out what changes I've made (haven't change font size though)

image

**Comment by FMog** [comment]
So just tested this, it looks really good. Only one thing I noticed was a slight mistake in the description on step 1:

screenshot 2015-02-05 14 58 07

As you can see it states "Sent it to us at hello@kano.me" when it should be "Send it to us"

Probably not even related to these changes, but it does need changing :)

**Comment by hzulla** [comment]
@TommySaehl ok, should I provide a patch with different pixel values or do you guys just want to sit down and twiddle with them on your own until you're happy?

Here's what you need to change:

* [font sizes and colours in the CSS](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/images/CSS/updater.css)
* [top margin of the headline](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L153)
* [bottom margin of the psa label container](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L284)
* [size of the stage label](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L331)
  (the stage label is centered within its box, so there is no "top margin" defined for it)

To make sure that the Gtk layout engine isn't confused, please note that these height values need to add up for the stage box:

[stage box height](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L309) = [stage label height](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L331) + [progress box height](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L340)

The window is currently layouted for 450 px height:

450px height = [header box height](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L133) + [stage box height](https://github.com/KanoComputing/kano-updater/blob/2b078987b20cb5f335ac3b9f9650e2b06d0eb1be/bin/kano-updater-gui#L309)

**Comment by TommySaehl** [comment]
@hzulla Sorry, but don't really know what you mean by "provide a patch with different pixel values".
Would be great if you'd able to implement those tweaks.

Thanks!

**Comment by hzulla** [comment]
I meant that modifying the layout now means changing those pixel values I referenced to in the previous comment.

My RPi is back on Tuesday. Will report back then with a patch.

**Comment by alex5imon** [comment]
@hzulla don't worry, we will do this. Thanks a lot for your work here, it has been extremely useful

**Comment by hzulla** [comment]
OK, thx. :-)

**Pull request merged**
