### PR TITLE
Adding hover to the lxpanel widget

### PR DESCRIPTION
**Pull request by pazdera**
Related to: https://github.com/KanoComputing/peldins/issues/2183

~~The icons need transparency change before merging:~~

~~all `widget-*` in https://github.com/KanoComputing/kano-updater/tree/master/lxpanel-plugin/images~~

cc @alex5imon @skarbat @neue

### CODE REVIEW

**Comment by skarbat** [comment]
looks ok to me @pazdera

**Comment by neue** [comment]
I don't have write access to this repo, so here they are:

widget-downloading-updates
widget-no-updates
widget-updates-available
widget-updates-downloaded

**Comment by radujipa** [comment]
cc @alex5imon

**Comment by alex5imon** [comment]
@neue @radujipa not sure we can add icons for the hover effect. It just uses the default effect

**Comment by pazdera** [comment]
Brilliant, thanks @neue!

@alex5imon You're right. The problem was that the icon's we have there now have a white border around them which becomes visible with the new hover effect.

**Comment by pazdera** [comment]
Committed the icons, this should be now ready to merge.

**Pull request merged**
