### PR TITLE
remove orphan dhcp client after migration to dhcpc5

### PR DESCRIPTION
**Pull request by skarbat**
Complements this PR: https://github.com/KanoComputing/kano-toolset/pull/254

### CODE REVIEW

**Comment by skarbat** [comment]
This PR has been tested by the automated upgrades with result=success

```
Start-Date: 2017-09-19  10:06:04
Commandline: /usr/bin/apt-get -y purge udhcpc
Purge: udhcpc:armhf (1.22.0-9+deb8u1)
End-Date: 2017-09-19  10:06:07
```

**Comment by skarbat** [comment]
This PR is to be replaced by this one: https://github.com/KanoComputing/kano-updater/pull/260

**Comment by radujipa** [comment]
@skarbat Should we close this PR and delete the branch?

**Comment by skarbat** [comment]
absolutely @radujipa , thanks for spotting!

**Pull request closed without merging**
