### PR TITLE
Fixes updates to latest Kano OS 2.2.0

### PR DESCRIPTION
**Pull request by radujipa**
This fixes broken updates currently in production to Kano OS 2.2.0 in the scenarios.

@tombettany @pazdera @convolu Could you please review this?

### CODE REVIEW

**Comment by tombettany** [comment]
@radujipa Great detective work. Looks good :shipit:

**Comment by convolu** [comment]
@radujipa I am responsible for doing now doing this properly, sorry :-). Looks good

**Comment by radujipa** [comment]
@tombettany couldn't have done it without you :)

 - added another fix in postinstall relating to kano-settings

**Comment by pazdera** [comment]
:shipit:

**Pull request merged**
