### PR TITLE
220->230: Install rsync during update

### PR DESCRIPTION
**Pull request by pazdera**
Related to: https://github.com/KanoComputing/peldins/issues/2216

cc @skarbat @alex5imon

### CODE REVIEW

**Comment by skarbat** [comment]
Looks good @pazdera , makes me think... should we say `no-install-recommends` as well here?

 * https://github.com/KanoComputing/kano-updater/blob/jessie/kano_updater/utils.py#L210-L211

**Comment by pazdera** [comment]
That's a good point, @skarbat.

**Comment by pazdera** [comment]
@skarbat Added it.

**Comment by skarbat** [comment]
great Radek! @pazdera

**Pull request merged**
