### PR TITLE
Adding a new step in the upgrade stage to fix homedire permissions

### PR DESCRIPTION
**Pull request by skarbat**
* A process will go through all home directories
   and apply KanoOS 2.0 permissions on sensitive files & dirs (tracker, logs)

### CODE REVIEW

**Comment by pazdera** [comment]
Looks good to me, @skarbat :-).

The only thing is that the people who have already updated to 2.0.0 and have the broken permissions will not benefit from this fix (the hook 134->200 hook won't run for them). I'm not sure whether that's what you intend to do?

**Comment by skarbat** [comment]
ah! Radek @pazdera, my understanding is that this issue is only appearing for users upgrading from 1.x? But can't hurt to do it for 2.0.0 -> 2.0.1 as well (just fixed). Besides, I have implemented it in a standalone tool, so in the worst case we can tell users to `sudo correct-homedir-permissions`.

**Comment by skarbat** [comment]
I am merging this one now @pazdera @Ealdwulf @alex5imon

**Comment by pazdera** [comment]
:+1: Thanks!

**Pull request merged**
