### PR TITLE
Bump version number for 3.0.1

### PR DESCRIPTION
**Pull request by Ealdwulf**
@skarbat @alex5imon @tombettany

### CODE REVIEW

**Comment by radujipa** [comment]
Don't forget the changes in peldins as well to go with this 👍

**Comment by tombettany** [comment]
👍

**Comment by Ealdwulf** [comment]
Thanks guys, merging...

**Comment by skarbat** [comment]
:+1:

**Comment by convolu** [comment]
A minor point here regarding the urgent updates. I'm not sure whether the logic has evolved since, but in the initial implementation we kept the last part of the version to 0, only to be bumped for packages in need of an urgent update. So the assumption was that the only thing that was bumped was the X and the Y in the X.Y.Z scheme.

**Comment by Ealdwulf** [comment]
Thanks Costas. I'll change it to 3.1.0

**Comment by alex5imon** [comment]
@Ealdwulf @convolu thanks guys!

**Pull request merged**
