### PR TITLE
Relaunch: Ensure that update proceeds after relaunch

### PR DESCRIPTION
**Pull request by tombettany**
During the relaunch of the updater, somehow the state gets reset to
`NO_UPDATES` which causes the relaunch to exit prematurely. Prevent this
from happening by forcing the state to be the value that it should be
after a relaunch.

@pazdera @convolu @radujipa to review

### CODE REVIEW

**Comment by pazdera** [comment]
Looks good, let's test

**Comment by radujipa** [comment]
Nice one!

**Comment by tombettany** [comment]
Updater should work after this fix so merging now.

**Comment by pazdera** [comment]
:shipit: Woot!

**Pull request merged**
