### PR TITLE
Remove initial docopt install

### PR DESCRIPTION
**Pull request by Ealdwulf**
This PR removes the initial attempt to install docopt. All version we can now update from already have docopt.

### CODE REVIEW

**Comment by Ealdwulf** [comment]
Done. Sadly, adding the changlog means this PR is no longer entirely composed of removed lines.

**Comment by tombettany** [comment]
I'm a little late to the game here but don't we want to add a Debian dependency on the Debian package of `docopt` rather than just relying on it being present on their systems?

**Comment by radujipa** [comment]
Yup, we'll do that once all pip pkgs will be converted to debs.

**Comment by tombettany** [comment]
👍

**Pull request merged**
