### PR TITLE
Update 134 to 200 post update scenario

### PR DESCRIPTION
**Pull request by convolu**
The name of the character has been changed

### CODE REVIEW

**Comment by convolu** [comment]
@pazdera @tombettany @alex5imon Could you please review?

**Comment by alex5imon** [comment]
Looks good to me (given that `judoka` exists as a parameter)

**Comment by tombettany** [comment]
Looks fine to me.

**Comment by convolu** [comment]
@alex5imon It should match this https://github.com/KanoComputing/kano-profile/blob/master/rules/avatar_generator/conf.json#L107 

Thanks, merging

**Pull request merged**
