### PR TITLE
Introduce urgent Priority and Scheduling

### PR DESCRIPTION
**Pull request by convolu**
* add `--urgent` cli option for the kano-updater check command
* add  `shutdown-window` for the kano-updater ui command
* add `set-scheduled` cli option for controlling the scheduled flag

### CODE REVIEW

**Comment by convolu** [comment]
@radujipa @tombettany @alex5imon This is the prio branch rebased on master. Let's do a review and merge as it is to get ahead on testing.

**Comment by alex5imon** [comment]
@convolu @tombettany @radujipa changes on documentation?

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by convolu** [comment]
An important thing to note for this PR is that most of the commits have been reviewed to be merged to this branch.

After this has merged we would need to merge the accompanying PRs:
* https://github.com/KanoComputing/kano-toolset/issues/149
* Bump kano-updater version to 2.2 
* Add dependency on the new version and merge https://github.com/KanoComputing/kano-desktop/pull/112

@alex5imon can update the documentation once this has merged :-).

**Comment by convolu** [comment]
I have added a commit that updates the OS Version, renames the scenarios and the package version.  Better do it whithin this PR .

@tombettany @radujipa @alex5imon Have I missed anything?

**Comment by radujipa** [comment]
Related https://github.com/KanoComputing/engage/issues/95 and https://github.com/KanoComputing/engage/issues/63

-

*How priorities and scheduling come together*

screen shot 2015-09-17 at 11 20 42

**Comment by convolu** [comment]
Excellent diagram @radujipa.

Thanks all, merging

**Pull request merged**
