### PR TITLE
Downgrading the improved FBTurbo driver to the previous version

### PR DESCRIPTION
**Pull request by skarbat**

### CODE REVIEW

**Comment by alex5imon** [comment]
Would this remove `/usr/share/X11/xorg.conf.d/999-fbturbo-improved.conf` for all users?

**Comment by skarbat** [comment]
Tested on the PI followed by a reboot. It certainly removes this file, and the previous one is installed: ```/usr/share/X11/xorg.conf.d/99-fbturbo.conf```

**Comment by pazdera** [comment]
I'd maybe put it into PreUpdate rather than post. Technically, it doesn't matter though.

**Comment by skarbat** [comment]
Makes sense @pazdera  . Done.

**Comment by pazdera** [comment]
Thank you, Albert :-).

**Pull request merged**
