### PR TITLE
Removed dialog asking to continue update after reboot

### PR DESCRIPTION
**Pull request by radujipa**
Related to https://github.com/KanoComputing/peldins/issues/2067, but this one is optional.

### CODE REVIEW

**Comment by tombettany** [comment]
So we want to continue regardless? If this is the desired behaviour then I would agree with the implementation but why are we doing it automatically?

**Comment by radujipa** [comment]
The main reason behind it is because since the user already agreed to update, we should finish the task rather than asking them again.

cc @alex5imon

**Comment by alex5imon** [comment]
I'm ok with it

**Comment by tombettany** [comment]
Fair enough. I'm okay with this PR then :+1:

**Pull request merged**
