### PR TITLE
Upload tracking data on update

### PR DESCRIPTION
**Pull request by pazdera**
Adding a new aux task.

cc @radujipa @tombettany @alex5imon

### CODE REVIEW

**Comment by alex5imon** [comment]
Is it worth doing here another `kano-sync --skip-kdesk --sync --backup --upload-tracking-data -s` ?

**Comment by pazdera** [comment]
Yeah, we could do the whole sync there. I'll add it.

**Comment by radujipa** [comment]
I tried testing this, however the Updater fails during the downloading phase due to broken packages..

To me, the PR looks good, since it's using `run_cmd_log` so we'll get logs and it's run in a subprocess so probably try/except is not really needed here, correct?

**Comment by pazdera** [comment]
@radujipa That should be correct.

**Comment by radujipa** [comment]
:shipit:

**Pull request merged**
