### PR TITLE
Updated scenario coverage of versions with 'Lovelace' OS name

### PR DESCRIPTION
**Pull request by radujipa**
Related to https://trello.com/c/qGwjC9zc/161-rc-updater-gets-stuck-updating-from-v3-8-0-version-is-too-old-you-need-to-reflash

@tombettany @skarbat

### CODE REVIEW

**Comment by skarbat** [comment]
I agree with Tom's comment - it's also likely `Lovelace` will become something else pretty soon?

**Comment by radujipa** [comment]
I would do it this way given that stripping it away would involve some more invasive changes to [os_version.py](https://github.com/KanoComputing/kano-updater/blob/master/kano_updater/os_version.py)...

**Comment by tombettany** [comment]
Hmm, yeah. Okay. Looking at the file it looks like this PR's approach might well be the safest way.

**Comment by skarbat** [comment]
I see your point @radujipa ... I can't find any other mention of the version name on the kit.
Perhaps we can go forward and we can add a QA test scenario for that. 👍

**Comment by radujipa** [comment]
I've just finished running through and update from 3.8.0 to latest rc with this fix and everything seems in order afterwards.

**Comment by radujipa** [comment]
[RC - Updater: Gets stuck updating from v3.8.0 - "[...] version is too old, you need to reflash [...]"](https://trello.com/c/qGwjC9zc/161-rc-updater-gets-stuck-updating-from-v3-8-0-version-is-too-old-you-need-to-reflash)

**Pull request merged**
