### PR TITLE
Move lots of the GUI to a module

### PR DESCRIPTION
**Pull request by tombettany**
A start towards moving all of the GUI elements into their own module to
simplify kano-updater-gui. Separates the GUI text into a completely
separate file to simplify keeping track of text copy.

@hzulla I've moved the text into `kano_updater_gui/text_en.py` if you are
looking to translate it - I hope this isn't too much of a problem :s

cc @carolineclark

### CODE REVIEW

**Comment by hzulla** [comment]
Actually, I wanted to use gettext instead of language-specific modules. See https://github.com/KanoComputing/kano-settings/pull/212

**Comment by tombettany** [comment]
@hzulla That's fine - I've just moved the text out into a separate file. We can make the file name very generic so isn't tied in with a language and then use gettext on that centralised file, if that's okay with you?

The main focus of this PR was to try to break up the `kano-updater-gui` executable so that it has more of a structure and make it easier to follow.

**Comment by tombettany** [comment]
@hzulla https://github.com/KanoComputing/kano-updater/commit/a4e206ede4989f9e8ba2fff824545f655139005f renames the module containing the text to be language neutral. We can use gettext on this if that is fine with you?

**Comment by hzulla** [comment]
Well, I'm waiting for a word from your team about that patch to kano-settings and whether using gettext is OK. (hint hint)

**Comment by tombettany** [comment]
@hzulla From speaking to the guys here, I think that gettext is the way to go. It is also a tool which none of us are particularly familiar with so your PR has gone under the radar. I'll discuss it with the guys.

**Comment by tombettany** [comment]
This PR is important to be able to easily do https://github.com/KanoComputing/peldins/issues/1582 and it also moves closer to the structure that we want so I think that this should be merged.

@hzulla this shouldn't interfere with [your PR](https://github.com/KanoComputing/kano-updater/pull/58) too much. It looks like the only thing that needs to be changed is to point:

 - [the header titles](https://github.com/hzulla/kano-updater/blob/186153aa7d1751f555f5ba21b10a48dbefc3771b/bin/kano-updater-gui#L149-L154)
 - [the header body](https://github.com/hzulla/kano-updater/blob/186153aa7d1751f555f5ba21b10a48dbefc3771b/bin/kano-updater-gui#L184-L243)
 - [the stage titles](https://github.com/hzulla/kano-updater/blob/186153aa7d1751f555f5ba21b10a48dbefc3771b/bin/kano-updater-gui#L326-L330)

To their point in [the new text copy file](https://github.com/KanoComputing/kano-updater/blob/860eae8c1989033e4db6e9cc82a7c7e083999487/kano_updater_gui/text.py)

And update the line numbers in [the translation file](https://github.com/hzulla/kano-updater/blob/186153aa7d1751f555f5ba21b10a48dbefc3771b/po/de.po)

@pazdera @carolineclark Any objections to what has been done here? If not I would like to merge for v1.3.3.

**Comment by hzulla** [comment]
https://github.com/KanoComputing/peldins/issues/1582 ?

**Comment by tombettany** [comment]
Merging now.

**Comment by tombettany** [comment]
@hzulla https://github.com/KanoComputing/peldins/issues/1582 is an internal ticket to add another stage to the updater: https://github.com/KanoComputing/kano-updater/pull/59

**Comment by hzulla** [comment]
@tombettany line numbers in the translation file are auto-generated and not relevant (they are only used by some PO-file editors to show translators the context within source).

I'll update & fix [PR #58] to make it mergeable.

**Pull request merged**
