### PR TITLE
Prune kano-content during the aux tasks

### PR DESCRIPTION
**Pull request by convolu**
Also run sync for all installed users on the kit

This PR is useful for https://github.com/KanoComputing/peldins/issues/2179

### CODE REVIEW

**Comment by convolu** [comment]
@pazdera @radujipa @tombettany What do you guys think?

**Comment by tombettany** [comment]
:shipit:

**Comment by pazdera** [comment]
Looks good to me :shipit:

**Comment by alex5imon** [comment]
Please merge :+1:

**Comment by convolu** [comment]
Thanks, going for it

**Pull request merged**
